# Generated by Django 5.2.5 on 2025-10-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=127)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('saturatedFat', models.FloatField(blank=True, null=True)),
                ('transFat', models.FloatField(blank=True, null=True)),
                ('cholesterol', models.FloatField(blank=True, null=True)),
                ('sodium', models.FloatField(blank=True, null=True)),
                ('carbohydrates', models.FloatField(blank=True, null=True)),
                ('fiber', models.FloatField(blank=True, null=True)),
                ('sugars', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('calcium', models.FloatField(blank=True, null=True)),
                ('iron', models.FloatField(blank=True, null=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('vitaminA', models.FloatField(blank=True, null=True)),
                ('vitaminC', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
